CREATE TABLE IF NOT EXISTS umbrella (
	Name character varying(60),
	Image character varying(100),
	DIY character varying(4),
	Buy INT,
	Sell INT,
	Color1 character varying(30),
	Color2 character varying(30),
	Source character varying(30),
	SourceNotes character varying(100),
	Catalog character varying(4)
);

COPY umbrella (Name, Image, DIY, Buy, Sell, Color1, Color2, Source, SourceNotes, Catalog)
FROM 'FILEPATH HERE' DELIMITER ',' CSV HEADER;