CREATE TABLE IF NOT EXISTS tool (
	Name character varying(255),
	Image character varying(255),
	Variation character varying(50),
	BodyTitle character varying(20),
	DIY character varying(30),
	Customize character varying(30),
	KitCost INT,
	Uses INT,
	Buy INT,
	Sell INT,
	Set character varying(30),
	Source character varying(200),
	SourceNotes character varying(200)
);

\COPY tool FROM 'C:\Users\yipin\go\src\github.com\Isabelle-Dev\isabelle-graphql\csv\tool.csv' DELIMITER ',' CSV HEADER;